homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 45.740679 
  longitude: 4.8518 
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 200
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr
  - platform: cert_expiry
    host: !secret base_url
# Text to speech
tts:
  - platform: google
    language: 'fr'

# Cloud
cloud:

google_assistant:
  project_id: !secret project_id
  client_id: !secret client_id
  access_token: !secret access_token
  agent_user_id: !secret agent_user_id
  #api_key: [a Homegraph API Key generated for the Google Actions project]
  expose_by_default: false
  exposed_domains:
    - light
  entity_config:
    light.salon_plafond:
      expose: true
      name: 'plafond du salon'
      room: salon
      #aliases:
      #  - 'plafond du salon'
    light.salon_prise:
      expose: true
      name: 'prise du salon'
      room: salon
    light.cuisine_plafond:
      expose: true
      name: 'plafond de la cuisine'
      room: cuisine
    light.cuisine_meuble:
      expose: true
      name: 'meuble de cuisine'
      room: cuisine
    cover.cuisine:
      expose: true
      name: 'volet de la cuisine'
      room: cuisine
    cover.salon_grand:
      expose: true
      name: 'grand volet'
      room: salon
    cover.salon_petit:
      expose: true
      name: 'petit volet'
      room: salon

brownpaperbag:
  host: 192.168.1.13
  port: 20000
  password: azerty123

light:
  - platform: brownpaperbag
    devices:
      - name: salon_plafond
        address: '02'
      - name: salon_prise
        address: '01'
      - name: cuisine_plafond
        address: '0012'
      - name: cuisine_meuble
        address: '0011'

cover:
  - platform: brownpaperbag
    devices:
      - name: salon_grand
        address: '08'
      - name: salon_petit
        address: '13'
      - name: cuisine
        address: '17'
      - name: bureau
        address: '06'
      - name: enfant
        address: '0113'
      - name: parents_porte
        address: '07'
      - name: parents_placard
        address: '16'

media_player:
  - platform: liveboxplaytv
    host: 192.168.1.101
    port: 8080
     
weblink:
  entities:
    - name: Router
      url: http://192.168.1.1/
      icon: mdi:router-wireless
    - name: Home Assistant
      url: https://www.home-assistant.io

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_key

logger:
  default: info

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
